const SUCCES = 200;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;
const CREATED_SUCCES = 201;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  SUCCES,
  CONFLICT_ERROR,
  CREATED_SUCCES,
  UNAUTHORIZED,
  FORBIDDEN,
};
